spring:
  config:
    activate:
      on-profile: prod
  application:
    name: sumte
  datasource:
    url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_DB}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    region: ap-northeast-2
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: sumte-file
      url-prefix: https://sumte-file.s3.ap-northeast-2.amazonaws.com
    stack:
      auto: false

# spring actuator 활용한 도커 헬스체크용
management:
  endpoints:
    web:
      exposure:
        include: health

app:
  host: ${EC2_HOST}

kakao:
  pay:
    secret-key: ${KAKAOPAY_SECRET_KEY}
    redirect:
      domain: ${DOMAIN}