spring:
  config:
    activate:
      on-profile: prod
  application:
    name: ouch
  datasource:
    url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${RDS_DB}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

openai:
  api-key: ${OPENAI_API_KEY}

jwt:
  secret: ${JWT_SECRET}

# spring actuator 활용한 도커 헬스체크용
management:
  endpoints:
    web:
      exposure:
        include: health